// Master catalog of all categories, sources, and filter rules.
// The backend fetches all enabled categories; the frontend filters client-side.

export const ALL_CATEGORIES = {
  "world-news": {
    label: "World News",
    description: "Major global events, geopolitics, diplomacy",
    icon: "globe",
    feeds: [
      { name: "BBC World", url: "https://feeds.bbci.co.uk/news/world/rss.xml" },
      { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml" },
      { name: "AP News", url: "https://feedx.net/rss/ap.xml" },
      { name: "Reuters World", url: "https://www.reutersagency.com/feed/?best-topics=world&post_type=best" },
      { name: "The Guardian World", url: "https://www.theguardian.com/world/rss" },
      { name: "NPR World", url: "https://feeds.npr.org/1004/rss.xml" },
      { name: "DW News", url: "https://rss.dw.com/rdf/rss-en-all" },
      { name: "France 24", url: "https://www.france24.com/en/rss" },
      { name: "The Economist", url: "https://www.economist.com/international/rss.xml" },
      { name: "Foreign Policy", url: "https://foreignpolicy.com/feed/" },
      { name: "The Diplomat", url: "https://thediplomat.com/feed/" },
      { name: "South China Morning Post", url: "https://www.scmp.com/rss/91/feed" },
      { name: "Nikkei Asia", url: "https://asia.nikkei.com/rss" },
      { name: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms" },
    ],
    newsApiQuery: "geopolitics OR international relations OR global economy OR trade war OR G7 OR NATO OR UN OR climate summit OR world leader",
    claudeFilter: `STRICT FILTER: Only include stories with GLOBAL significance — geopolitics, international diplomacy, trade, macroeconomics, wars/conflicts between nations, major policy shifts, climate agreements, global health crises, etc. ABSOLUTELY EXCLUDE: celebrity news, entertainment, royal family gossip, sports, Hollywood, music artists, influencers, reality TV, personal scandals, local crime, domestic violence, local accidents, human interest stories, and anything that only affects a single city or community. If a story is primarily about a celebrity or entertainer, it does NOT belong here regardless of the outlet that published it. If in doubt, leave it out.`,
  },

  "automotive-ev-battery": {
    label: "Auto / EV / Battery",
    description: "Electric vehicles, batteries, charging, automotive industry",
    icon: "car",
    feeds: [
      { name: "Electrive", url: "https://www.electrive.com/feed/" },
      { name: "InsideEVs", url: "https://www.insideevs.com/rss/news/" },
      { name: "CleanTechnica", url: "https://cleantechnica.com/feed/" },
      { name: "Electrek", url: "https://electrek.co/feed/" },
      { name: "Green Car Reports", url: "https://www.greencarreports.com/rss" },
      { name: "Charged EVs", url: "https://chargedevs.com/feed/" },
      { name: "Automotive News", url: "https://www.autonews.com/arc/outboundfeeds/rss/?outputType=xml" },
      { name: "Car and Driver", url: "https://www.caranddriver.com/rss/all.xml/" },
      { name: "Motor Trend", url: "https://www.motortrend.com/feed/" },
      { name: "Autocar", url: "https://www.autocar.co.uk/rss" },
      { name: "Top Gear", url: "https://www.topgear.com/rss.xml" },
      { name: "The Drive", url: "https://www.thedrive.com/feed" },
      { name: "Jalopnik", url: "https://jalopnik.com/rss" },
      { name: "Automotive Dive", url: "https://www.automotivedive.com/feeds/news/" },
    ],
    newsApiQuery: "electric vehicle OR EV battery OR automotive technology OR Tesla OR charging OR autonomous driving",
  },

  "tech-ai": {
    label: "Tech / AI",
    description: "Artificial intelligence, tech industry, software, hardware",
    icon: "cpu",
    feeds: [
      { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
      { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
      { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index" },
      { name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/" },
      { name: "Wired", url: "https://www.wired.com/feed/rss" },
      { name: "The Register", url: "https://www.theregister.com/headlines.atom" },
      { name: "Hacker News", url: "https://hnrss.org/frontpage" },
      { name: "Engadget", url: "https://www.engadget.com/rss.xml" },
      { name: "ZDNet", url: "https://www.zdnet.com/news/rss.xml" },
      { name: "VentureBeat", url: "https://venturebeat.com/feed/" },
      { name: "The Information", url: "https://www.theinformation.com/feed" },
      { name: "9to5Mac", url: "https://9to5mac.com/feed/" },
      { name: "Android Authority", url: "https://www.androidauthority.com/feed/" },
      { name: "Tom's Hardware", url: "https://www.tomshardware.com/feeds/all" },
      { name: "AnandTech", url: "https://www.anandtech.com/rss/" },
      { name: "Slashdot", url: "https://rss.slashdot.org/Slashdot/slashdotMain" },
    ],
    newsApiQuery: "artificial intelligence OR AI startup OR machine learning OR tech company OR OpenAI OR Google AI",
  },

  "finance-markets": {
    label: "Finance / Markets",
    description: "Stock markets, banking, global finance, monetary policy",
    icon: "chart",
    feeds: [
      { name: "Financial Times", url: "https://www.ft.com/?format=rss" },
      { name: "Bloomberg", url: "https://feeds.bloomberg.com/markets/news.rss" },
      { name: "CNBC", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114" },
      { name: "MarketWatch", url: "https://feeds.marketwatch.com/marketwatch/topstories/" },
      { name: "Yahoo Finance", url: "https://finance.yahoo.com/news/rssindex" },
      { name: "Investopedia", url: "https://www.investopedia.com/feedbuilder/feed/getfeed/?feedName=rss_headline" },
      { name: "Seeking Alpha", url: "https://seekingalpha.com/market_currents.xml" },
      { name: "The Motley Fool", url: "https://www.fool.com/feeds/index.aspx" },
      { name: "Barron's", url: "https://www.barrons.com/feed" },
      { name: "WSJ Markets", url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml" },
    ],
    newsApiQuery: "stock market OR federal reserve OR interest rates OR IPO OR Wall Street OR global finance",
  },

  "science-space": {
    label: "Science / Space",
    description: "Scientific discoveries, space exploration, research breakthroughs",
    icon: "rocket",
    feeds: [
      { name: "NASA", url: "https://www.nasa.gov/rss/dyn/breaking_news.rss" },
      { name: "Space.com", url: "https://www.space.com/feeds/all" },
      { name: "Scientific American", url: "https://rss.sciam.com/ScientificAmerican-Global" },
      { name: "Nature", url: "https://www.nature.com/nature.rss" },
      { name: "Science Daily", url: "https://www.sciencedaily.com/rss/all.xml" },
      { name: "New Scientist", url: "https://www.newscientist.com/feed/home/" },
      { name: "Phys.org", url: "https://phys.org/rss-feed/" },
      { name: "SpaceNews", url: "https://spacenews.com/feed/" },
      { name: "Ars Technica Science", url: "https://feeds.arstechnica.com/arstechnica/science" },
      { name: "Live Science", url: "https://www.livescience.com/feeds/all" },
    ],
    newsApiQuery: "space exploration OR scientific discovery OR NASA OR physics OR climate science OR biology research",
  },

  "energy-climate": {
    label: "Energy / Climate",
    description: "Renewable energy, climate policy, sustainability, oil & gas",
    icon: "leaf",
    feeds: [
      { name: "Carbon Brief", url: "https://www.carbonbrief.org/feed/" },
      { name: "Renewables Now", url: "https://renewablesnow.com/news/feed/" },
      { name: "PV Magazine", url: "https://www.pv-magazine.com/feed/" },
      { name: "GreenBiz", url: "https://www.greenbiz.com/rss.xml" },
      { name: "Energy Monitor", url: "https://www.energymonitor.ai/feed/" },
      { name: "Utility Dive", url: "https://www.utilitydive.com/feeds/news/" },
      { name: "Canary Media", url: "https://www.canarymedia.com/feed" },
      { name: "Grist", url: "https://grist.org/feed/" },
      { name: "Inside Climate News", url: "https://insideclimatenews.org/feed/" },
      { name: "Oil Price", url: "https://oilprice.com/rss/main" },
    ],
    newsApiQuery: "renewable energy OR solar power OR wind energy OR climate change policy OR carbon emissions OR oil price",
  },

  "health-biotech": {
    label: "Health / Biotech",
    description: "Healthcare, biotech, pharmaceuticals, medical research",
    icon: "heart",
    feeds: [
      { name: "STAT News", url: "https://www.statnews.com/feed/" },
      { name: "Fierce Biotech", url: "https://www.fiercebiotech.com/rss/xml" },
      { name: "Endpoints News", url: "https://endpts.com/feed/" },
      { name: "BioPharma Dive", url: "https://www.biopharmadive.com/feeds/news/" },
      { name: "Medical News Today", url: "https://www.medicalnewstoday.com/newsfeeds/rss" },
      { name: "The Lancet", url: "https://www.thelancet.com/rssfeed/lancet_current.xml" },
      { name: "Health Affairs", url: "https://www.healthaffairs.org/action/showFeed?type=etoc&feed=rss&jc=hlthaff" },
      { name: "WHO News", url: "https://www.who.int/rss-feeds/news-english.xml" },
    ],
    newsApiQuery: "biotech OR pharmaceutical OR FDA approval OR clinical trial OR gene therapy OR healthcare policy",
  },

  "crypto-web3": {
    label: "Crypto / Web3",
    description: "Cryptocurrency, blockchain, DeFi, NFTs, regulation",
    icon: "coin",
    feeds: [
      { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/" },
      { name: "The Block", url: "https://www.theblock.co/rss.xml" },
      { name: "Decrypt", url: "https://decrypt.co/feed" },
      { name: "CoinTelegraph", url: "https://cointelegraph.com/rss" },
      { name: "Bitcoin Magazine", url: "https://bitcoinmagazine.com/feed" },
      { name: "Blockworks", url: "https://blockworks.co/feed" },
      { name: "DL News", url: "https://www.dlnews.com/rss/" },
    ],
    newsApiQuery: "cryptocurrency OR bitcoin OR ethereum OR blockchain OR DeFi OR crypto regulation",
  },

  "startups-vc": {
    label: "Startups / VC",
    description: "Venture capital, fundraising, startup ecosystem",
    icon: "briefcase",
    feeds: [
      { name: "TechCrunch Startups", url: "https://techcrunch.com/category/startups/feed/" },
      { name: "Crunchbase News", url: "https://news.crunchbase.com/feed/" },
      { name: "Pitchbook News", url: "https://pitchbook.com/feed" },
      { name: "SaaStr", url: "https://www.saastr.com/feed/" },
      { name: "Both Sides of the Table", url: "https://bothsidesofthetable.com/feed" },
      { name: "First Round Review", url: "https://review.firstround.com/feed.xml" },
      { name: "Y Combinator Blog", url: "https://www.ycombinator.com/blog/rss/" },
    ],
    newsApiQuery: "venture capital OR startup funding OR Series A OR IPO OR unicorn startup OR Y Combinator",
  },

  "cybersecurity": {
    label: "Cybersecurity",
    description: "Security breaches, vulnerabilities, cyber threats, privacy",
    icon: "shield",
    feeds: [
      { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/" },
      { name: "The Hacker News", url: "https://feeds.feedburner.com/TheHackersNews" },
      { name: "Dark Reading", url: "https://www.darkreading.com/rss.xml" },
      { name: "Bleeping Computer", url: "https://www.bleepingcomputer.com/feed/" },
      { name: "SecurityWeek", url: "https://www.securityweek.com/feed/" },
      { name: "Threatpost", url: "https://threatpost.com/feed/" },
      { name: "SC Media", url: "https://www.scmagazine.com/feed" },
    ],
    newsApiQuery: "cybersecurity OR data breach OR ransomware OR vulnerability OR cyber attack OR privacy",
  },

  "asia-pacific": {
    label: "Asia-Pacific",
    description: "News from Southeast Asia, China, Japan, Korea, India, Oceania",
    icon: "map",
    feeds: [
      { name: "South China Morning Post", url: "https://www.scmp.com/rss/91/feed" },
      { name: "Nikkei Asia", url: "https://asia.nikkei.com/rss" },
      { name: "The Diplomat", url: "https://thediplomat.com/feed/" },
      { name: "Channel News Asia", url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml" },
      { name: "Bangkok Post", url: "https://www.bangkokpost.com/rss/data/topstories.xml" },
      { name: "The Straits Times", url: "https://www.straitstimes.com/news/asia/rss.xml" },
      { name: "Japan Times", url: "https://www.japantimes.co.jp/feed/" },
      { name: "Korea Herald", url: "https://www.koreaherald.com/common/rss_xml.php" },
      { name: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms" },
      { name: "ABC Australia", url: "https://www.abc.net.au/news/feed/51120/rss.xml" },
    ],
    newsApiQuery: "Asia Pacific OR ASEAN OR China policy OR Japan economy OR India OR Southeast Asia OR Korea",
    claudeFilter: `Focus on stories with regional or global significance from the Asia-Pacific region. Include geopolitics, trade, economic developments, major policy changes, and significant events. Exclude local crime, celebrity gossip, and minor domestic stories.`,
  },

  "sports": {
    label: "Sports",
    description: "Major sports news, football, basketball, tennis, Olympics, esports",
    icon: "trophy",
    feeds: [
      { name: "ESPN", url: "https://www.espn.com/espn/rss/news" },
      { name: "BBC Sport", url: "https://feeds.bbci.co.uk/sport/rss.xml" },
      { name: "Sky Sports", url: "https://www.skysports.com/rss/12040" },
      { name: "Bleacher Report", url: "https://bleacherreport.com/articles/feed" },
      { name: "The Athletic", url: "https://theathletic.com/feed/" },
      { name: "Sports Illustrated", url: "https://www.si.com/rss/si_topstories.rss" },
      { name: "CBS Sports", url: "https://www.cbssports.com/rss/headlines/" },
      { name: "Dexerto Esports", url: "https://www.dexerto.com/feed/" },
    ],
    newsApiQuery: "football OR basketball OR tennis OR Olympics OR FIFA OR NBA OR esports OR Champions League",
  },

  "school-education": {
    label: "School & Education",
    description: "Education news, college admissions, student life, learning trends",
    icon: "book",
    feeds: [
      { name: "Education Week", url: "https://www.edweek.org/feed" },
      { name: "Inside Higher Ed", url: "https://www.insidehighered.com/rss/feed" },
      { name: "The Hechinger Report", url: "https://hechingerreport.org/feed/" },
      { name: "EdSurge", url: "https://www.edsurge.com/articles_rss" },
      { name: "Times Higher Education", url: "https://www.timeshighereducation.com/rss" },
      { name: "Chronicle of Higher Ed", url: "https://www.chronicle.com/feed" },
    ],
    newsApiQuery: "education policy OR college admissions OR student OR university OR school OR online learning OR SAT OR scholarship",
  },

  "nature-science": {
    label: "Nature & Science",
    description: "Biology, physics, chemistry, wildlife, environment, natural world",
    icon: "leaf",
    feeds: [
      { name: "National Geographic", url: "https://www.nationalgeographic.com/feed" },
      { name: "Nature", url: "https://www.nature.com/nature.rss" },
      { name: "Science Magazine", url: "https://www.science.org/rss/news_current.xml" },
      { name: "New Scientist", url: "https://www.newscientist.com/feed/home/" },
      { name: "Phys.org", url: "https://phys.org/rss-feed/" },
      { name: "Live Science", url: "https://www.livescience.com/feeds/all" },
      { name: "Science Daily", url: "https://www.sciencedaily.com/rss/all.xml" },
      { name: "Smithsonian Magazine", url: "https://www.smithsonianmag.com/rss/latest_articles/" },
      { name: "IFLScience", url: "https://www.iflscience.com/feed" },
    ],
    newsApiQuery: "biology discovery OR physics breakthrough OR chemistry OR wildlife OR nature OR animal species OR ocean OR environment research",
  },

  "music-arts": {
    label: "Music & Arts",
    description: "Music, concerts, movies, TV, streaming, art, culture",
    icon: "music",
    feeds: [
      { name: "Pitchfork", url: "https://pitchfork.com/feed/feed-news/rss" },
      { name: "Rolling Stone", url: "https://www.rollingstone.com/feed/" },
      { name: "Billboard", url: "https://www.billboard.com/feed/" },
      { name: "NME", url: "https://www.nme.com/feed" },
      { name: "Consequence of Sound", url: "https://consequence.net/feed/" },
      { name: "Variety", url: "https://variety.com/feed/" },
      { name: "The Hollywood Reporter", url: "https://www.hollywoodreporter.com/feed/" },
      { name: "Deadline", url: "https://deadline.com/feed/" },
    ],
    newsApiQuery: "music album OR concert tour OR movie release OR streaming OR Grammy OR Oscar OR art exhibition OR Netflix OR Spotify",
  },
};

// Default enabled categories
export const DEFAULT_ENABLED = [
  "world-news",
  "automotive-ev-battery",
  "tech-ai",
];
